name:                imageCompressor
version:             0.1.0.0
github:              ""
license:             BSD3
author:              "Clement Harel"
maintainer:          "clement.harel@epitech.eu"
copyright:           "2019 Clement Harel"

description:         Epitech project

dependencies:
- base >= 4.7 && < 5
- random

library:
  source-dirs: src

executables:
  imageCompressor:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - imageCompressor

tests:
  imageCompressor-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - imageCompressor
